version: "3"

services:
  db:
    container_name: db
    image: postgres
    restart: always # restart if container fails
    env_file: ./backend/.env
    environment:
      TZ: Europe/Paris
      PGTZ: Europe/Paris
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backend:
    build: ./backend
    container_name: backend
    env_file: ./backend/.env
    volumes:
      - ./backend:/usr/src/app
    command: /bin/sh -c "npm install && npm run start:dev"
    ports:
      - 9000:9000
    depends_on:
      - db

  frontend:
    container_name: frontend
    build: ./frontend
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/usr/src/app
      - ./frontend/node_modules:/usr/src/app/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - 9001:9001
    depends_on:
      - backend

volumes:
  postgres-data: {}
